//let astral_objects = document.querySelectorAll(".carr-object");

const nav_cont = document.querySelector('#obs-nav')
const nav_input = document.querySelector('#navbar-input')
const wanted_btns = document.querySelectorAll(".obs-nav-bar-wantbtn")
const wanted_btn_visibles = document.querySelector('#obs-navbar-visibles')
const wanted_btn_showall = document.querySelector('#obs-navbar-showall')

let showing = "visible" //variable parameter for what type of thing the user wants to see. (visible/all)
let reset = 0 

let planetsready = false;
let restofdatasready = false;

window.addEventListener("planetsready" , ()=> {
   planetsready = true;
   verification_if_ready()
})

window.addEventListener("otherready" , () => {
   restofdatasready = true;
   verification_if_ready()
})

function verification_if_ready(){
   if (planetsready && restofdatasready ){
      async function display_carrousel(){
      if (reset != 0){
         nav_cont.innerHTML = '';
         let borderdiv = document.createElement("div");
         borderdiv.classList.add("carrousel-card")
         let lastborderdiv = document.createElement("div");
         lastborderdiv.classList.add("carrousel-card")
         nav_cont.appendChild(borderdiv)
         nav_cont.appendChild(lastborderdiv)
      }
      for (const type in celestial_objects) {
         for (const spaceobject in celestial_objects[type]){
            if (showing != "all") {
               if (celestial_objects[type][spaceobject].infos.visibility != "red") {
                  
                  let newdiv = document.createElement("div");
                  newdiv.classList.add("carrousel-card");
                  let lastdiv = nav_cont.lastElementChild
                  nav_cont.insertBefore(newdiv , lastdiv)
                  
                  let newimg = document.createElement("img");
                  newimg.src = celestial_objects[type][spaceobject].img
                  newimg.classList.add("carr-object");
                  newimg.title = celestial_objects[type][spaceobject].name
                  newimg.category = celestial_objects[type][spaceobject].histype;
                  newdiv.appendChild(newimg)
               }
            }
            else if (showing == "all") {
               //tried to create a function to do thedisplay but not worked... I'm bad at this..
                  let newdiv = document.createElement("div");
                  newdiv.classList.add("carrousel-card");
                  let lastdiv = nav_cont.lastElementChild
                  nav_cont.insertBefore(newdiv , lastdiv)
                  
                  let newimg = document.createElement("img");
                  newimg.src = celestial_objects[type][spaceobject].img
                  newimg.classList.add("carr-object");
                  newimg.title = celestial_objects[type][spaceobject].name
                  newimg.category = celestial_objects[type][spaceobject].histype;
                  newdiv.appendChild(newimg)
            }
         }
      }

         window.dispatchEvent(new Event("displaydone"));
      }
      display_carrousel()

      wanted_btns.forEach(btn => {
         btn.addEventListener("click", (clickedon)=>{
            reset = 1;
            let clicked_btn_id = clickedon.target.id;
            if (clicked_btn_id.includes("all")){
               showing = "all";
               display_carrousel()
               nav_cont.children[2].scrollIntoView({
                  behavior: "smooth",
                  inline: "center",
                  block: "nearest"
            })
               indextextholder.innerHTML = ""
            }
            else {
               showing = "visible";
               display_carrousel()
               nav_cont.children[2].scrollIntoView({
                  behavior: "smooth",
                  inline: "center",
                  block: "nearest"
               })
               indextextholder.innerHTML = "" 
            }
         })
      })

      nav_input.addEventListener("input" , ()=> {
         indextextholder.innerHTML = "" //remove if there is a previous text generated by a click so only one is shown.
         let navobjects = document.querySelectorAll(".carr-object");
         navobjects.forEach(cardobject => {
            cardobject.classList.remove("carr-object-selected")
         })

         //Previous code is in order to clean the possible previous focus on an object.

         let current_input = nav_input.value.toLowerCase().replaceAll(" ", "");

         let new_astral_objects = document.querySelectorAll(".carr-object");
         new_astral_objects.forEach(card => {
            let adapted_title = card.title.toLowerCase().replaceAll(" ", "");
            adapted_title.includes(current_input) ? card.parentElement.style.display = "flex" : card.parentElement.style.display ="none";
            let visibleCards = document.querySelectorAll(".carrousel-card:not([style*='display: none'])"); //Chatgpt help for the selector.
            visibleCards[1].scrollIntoView({
               behavior: "smooth",
               inline: "center",
               block: "nearest"
            })
         })
      })

      sessionStorage.setItem("celestialdatas", JSON.stringify(celestial_objects));
         
   }
}
