let obsbtnlist = document.querySelectorAll(".obs-svg-btn");

obsbtnlist.forEach(btn => {
   btn.addEventListener("click",() => {
      
      obsbtnlist.forEach(b => b.classList.remove("obs-btn-selected"));

      btn.classList.add("obs-btn-selected");
   });
});

let navbtnlist = document.querySelectorAll(".nav-bar-svg-btn");

navbtnlist.forEach(btn => {
   btn.addEventListener("click", ()=> {
      navbtnlist.forEach(b => b.classList.remove("nav-btn-selected"));

      btn.classList.add("nav-btn-selected")
   })
})

let container = document.getElementById("obs-nav")

container.scroll({
   left:container.clientWidth / 2,
   behavior:"smooth"
})

//Draggable carrousel from first Lookup project
const scrollwind = document.getElementById("obs-nav")

let isDragging = false;
let startX;
let scrollStart;

scrollwind.addEventListener("mousedown", e => {
   isDragging = true;
   startX = e.clientX;
   scrollStart = scrollwind.scrollLeft;
});

scrollwind.addEventListener("mousemove", e => {
   if (!isDragging) return;
   
   let distance = e.clientX - startX;
   scrollwind.scrollLeft = scrollStart - distance;
});

scrollwind.addEventListener("mouseup", () => {
   isDragging = false;
});

scrollwind.addEventListener("mouseleave", () => {
   isDragging = false;
});


//carrousel of astral objects

const indextextholder = document.querySelector("#obs-nav-infos") 

window.addEventListener("displaydone" , ()=>{
   
   const startelement = nav_cont.children[2];
   startelement.scrollIntoView({behavior:"smooth" , block: "center"})
   
   let astral_objects = document.querySelectorAll(".carr-object");

   astral_objects.forEach(btn => {
      btn.addEventListener("click", ()=> {

         if (btn.classList.contains("carr-object-selected")){
            open("./html/eyesobs.html?objecttype=" + btn.category + "&objectid=" + btn.title.toLowerCase() )
            return;
         }

         astral_objects.forEach(b => b.classList.remove("carr-object-selected"));

         btn.classList.add("carr-object-selected")
      });


   })


   astral_objects.forEach(card => {
      card.addEventListener("click", ()=>{
         const x =
            card.offsetLeft
            - container.clientWidth / 2
            + card.clientWidth /2;
   
         container.scrollTo({
            left: x,
            behavior: "smooth"      
         });

      indextextholder.innerHTML = "" //remove if there is a previous text generated by a click so only one is shown.

      let textholder = document.createElement("h3");
      let status_light = document.createElement("div");
      let type = card.category
      let thename = card.title.toLowerCase().replaceAll(" ", "_")
      console.log(thename)
      status_light.classList.add("status-light" , `${celestial_objects[type][thename].infos.visibility}`)

      let newtext = document.createTextNode(card.title);
      textholder.appendChild(newtext)
      textholder.appendChild(status_light)
      indextextholder.appendChild(textholder)

      })
   })

   if (showing == "visible"){
      wanted_btns.forEach(btn => {
         btn.classList.remove("wanted-btn-selected")
      })
      wanted_btn_visibles.classList.add("wanted-btn-selected")
   }
   else{
      wanted_btns.forEach(btn => {
         btn.classList.remove("wanted-btn-selected")
      })
      wanted_btn_showall.classList.add('wanted-btn-selected')
   }

      
})
const hiddensettings = document.querySelectorAll(".hidden")
const settings_panel = document.querySelector("#settings-panel")

function settings_tab(btnname){

   if (settings_panel.classList.contains("open")){
      settings_panel.classList.remove("open")
      navbtnlist[0].classList.add("nav-btn-selected") //help
      console.log(navbtnlist[0])
      hiddensettings.forEach(hidden_elem => {
         hidden_elem.classList.add("hidden")
      })

   }
   else{
      if (btnname == "set") {
         settings_panel.classList.add("open")
         hiddensettings.forEach(hidden_elem => {
            hidden_elem.classList.remove("hidden")
         })
      }
   }

}

const colorboxes = document.querySelectorAll(".color-box")
// All affected by main color elements of the page
const navbar = document.querySelector("#nav-bar")
const weathercont = document.querySelector("#weather-cont")
const obscont = document.querySelector("#obs-headercont")
const settingspanel = document.querySelector("#settings-panel")
const elemlist = [navbar , weathercont , obscont , settings_panel]

colorboxes.forEach(box => {
   box.addEventListener("click" , ()=> {

      if (!(box.classList.contains("selected"))){
         colorboxes.forEach(b => b.classList.remove("selected"))
         box.classList.add("selected")
         }
      
      let selectedcolor = box.classList[1]
      
      elemlist.forEach(elem => {
         elem.classList.remove(elem.classList[0])
         elem.classList.add(selectedcolor)
      })
         
      sessionStorage.setItem("maincolor" , selectedcolor);

   })
})

//Make the maincolor still remains between pages until session is over.
let actualmaincolor = sessionStorage.getItem("maincolor");
if (actualmaincolor != null){
   elemlist.forEach(elem => {
      elem.classList.remove(elem.classList[0])
      elem.classList.add(actualmaincolor)
   })  

   colorboxes.forEach(box => {
      box.classList.remove("selected")
      if (box.classList.contains(actualmaincolor)){
         box.classList.add("selected")
      }
   })
}
