let obsbtnlist = document.querySelectorAll(".obs-svg-btn");

obsbtnlist.forEach(btn => {
   btn.addEventListener("click",() => {
      
      obsbtnlist.forEach(b => b.classList.remove("obs-btn-selected"));

      btn.classList.add("obs-btn-selected");
   });
});

let navbtnlist = document.querySelectorAll(".nav-bar-svg-btn");

navbtnlist.forEach(btn => {
   btn.addEventListener("click", ()=> {
      navbtnlist.forEach(b => b.classList.remove("nav-btn-selected"));

      btn.classList.add("nav-btn-selected")
   })
})

let container = document.getElementById("obs-nav")

container.scroll({
   left:container.clientWidth / 2,
   behavior:"smooth"
})

//Draggable carrousel from first Lookup project
const scrollwind = document.getElementById("obs-nav")

let isDragging = false;
let startX;
let scrollStart;

scrollwind.addEventListener("mousedown", e => {
   isDragging = true;
   startX = e.clientX;
   scrollStart = scrollwind.scrollLeft;
});

scrollwind.addEventListener("mousemove", e => {
   if (!isDragging) return;
   
   let distance = e.clientX - startX;
   scrollwind.scrollLeft = scrollStart - distance;
});

scrollwind.addEventListener("mouseup", () => {
   isDragging = false;
});

scrollwind.addEventListener("mouseleave", () => {
   isDragging = false;
});


//carrousel of astral objects

const indextextholder = document.querySelector("#obs-nav-infos") 

window.addEventListener("displaydone" , ()=>{
   
   const startelement = nav_cont.children[2];
   startelement.scrollIntoView({behavior:"smooth" , block: "center"})
   
   let astral_objects = document.querySelectorAll(".carr-object");

   astral_objects.forEach(btn => {
      btn.addEventListener("click", ()=> {

         if (btn.classList.contains("carr-object-selected")){
            open("./html/eyesobs.html?objecttype=" + btn.category + "&objectid=" + btn.title.toLowerCase() )
            return;
         }

         astral_objects.forEach(b => b.classList.remove("carr-object-selected"));

         btn.classList.add("carr-object-selected")
      });


   })



   
   astral_objects.forEach(card => {
      card.addEventListener("click", ()=>{
         const x =
            card.offsetLeft
            - container.clientWidth / 2
            + card.clientWidth /2;
   
         container.scrollTo({
            left: x,
            behavior: "smooth"      
         });

      indextextholder.innerHTML = "" //remove if there is a previous text generated by a click so only one is shown.

      let textholder = document.createElement("h3");
      let status_light = document.createElement("div");
      let type = card.category
      let thename = card.title.toLowerCase().replaceAll(" ", "")
      status_light.classList.add("status-light" , `${celestial_objects[type][thename].infos.visibility}`)

      let newtext = document.createTextNode(card.title);
      textholder.appendChild(newtext)
      textholder.appendChild(status_light)
      indextextholder.appendChild(textholder)

      })
   })

   if (showing == "visible"){
      wanted_btns.forEach(btn => {
         btn.classList.remove("wanted-btn-selected")
      })
      wanted_btn_visibles.classList.add("wanted-btn-selected")
   }
   else{
      wanted_btns.forEach(btn => {
         btn.classList.remove("wanted-btn-selected")
      })
      wanted_btn_showall.classList.add('wanted-btn-selected')
   }

})

